version: "3"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    networks:
    - jenkins-net
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ".\\vol\\nginx\\default.conf:/etc/nginx/conf.d/default.conf"
    - ".\\vol\\nginx\\ssl:/etc/nginx/ssl"
    - ".\\vol\\nginx\\html:/usr/share/nginx/html"
    
  jenkins:
    image: jenkins:alpine
    container_name: jenkins
    networks:
    - jenkins-net
    volumes:
    - ".\\vol\\jenkins\\home:/var/jenkins_home"

networks:
  jenkins-net:
